### PR TITLE
Change two occurrences of CrigGIS to CritGIS

### PR DESCRIPTION
**Pull request by almccon**

### CODE REVIEW

**Comment by geoglrb** [comment]
Thanks!

**Comment by jethatch** [comment]
But Alan... what if I had *meant* CrigGIS... It's the new, new, new thing!

(thank you)

**Comment by almccon** [comment]
@jethatch well, the other possibility I considered is that it could be a misspelling of CraigGIS. [would tag Dr. Dalton here if I knew his github handle...]

**Comment by jethatch** [comment]
Oh, that's beautiful. Sadly, I don't think he has one.

**Comment by geoglrb** [comment]
Wait, isn't he a member of 'the organization'?

-L

**Pull request merged**
